# Generated by Django 3.1.3 on 2020-11-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('First_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('Patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('Email', models.CharField(max_length=255)),
                ('Phone_number', models.IntegerField()),
                ('Object', models.CharField(max_length=255, verbose_name='Объект оценки')),
                ('Aim', models.CharField(max_length=255, verbose_name='Цель оценки')),
                ('Address', models.CharField(max_length=255, verbose_name='Адрес объекта оценки')),
                ('Price', models.IntegerField(verbose_name='Цена покупки')),
                ('Comment', models.CharField(max_length=255, verbose_name='Комментарии')),
            ],
        ),
    ]
