# Generated by Django 3.1.3 on 2020-11-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalcompsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('eval_object', models.CharField(max_length=255, verbose_name='Объект оценки')),
                ('aim', models.CharField(max_length=255, verbose_name='Цель оценки')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес объекта оценки')),
                ('price', models.IntegerField(verbose_name='Цена покупки')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарии')),
            ],
        ),
        migrations.DeleteModel(
            name='Request_list',
        ),
    ]
