# Generated by Django 3.1.3 on 2020-11-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalcompsite', '0002_auto_20201124_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
