# Generated by Django 3.1.3 on 2020-12-09 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evalcompsite', '0005_apartment_house_land'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарии')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
    ]
